name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/** 
  pull_request:
    branches:
      - actions
      - test
    paths-ignore:
      - README.md
      - docs/** 
  
jobs:
  ci-pipeline:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: build step
        run: |
          echo "Building the application..."
          make build-api
      - name: test step
        run: |
          echo "Running tests..."
          make test-api
      - name: lint step
        run: |
          echo "Linting the code..."
          make lint-api
      - name: docker-push step
        run: |
          echo "Pushing into Docker Hub..."
          make compose-push
